# Generated by Django 4.0.2 on 2022-03-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('bucket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.bucket')),
                ('limit', models.FloatField()),
            ],
            bases=('budget.bucket',),
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('bucket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.bucket')),
            ],
            bases=('budget.bucket',),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('bucket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.bucket')),
                ('plan', models.FloatField(default=0)),
            ],
            bases=('budget.bucket',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.FloatField(default=0)),
                ('expenses', models.FloatField(default=0)),
                ('family', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='users.family')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source_transaction', to='budget.bucket')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='budget.bucket')),
            ],
        ),
        migrations.AddField(
            model_name='bucket',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.wallet'),
        ),
    ]
