# Generated by Django 4.0.2 on 2022-03-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transaction', to='budget.bucket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='budget.bucket'),
        ),
    ]
