# Generated by Django 4.0.2 on 2022-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
