# Generated by Django 4.0.2 on 2022-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incomes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
