# Generated by Django 4.0.2 on 2022-02-24 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_incomes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 14, 21, 2, 850301, tzinfo=utc)),
        ),
    ]
