# Generated by Django 4.0.2 on 2022-02-24 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_incomes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
