# Generated by Django 4.0.2 on 2022-02-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_incomes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budget.wallet'),
            preserve_default=False,
        ),
    ]
