# Generated by Django 4.0.2 on 2022-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_incomes_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
