# Generated by Django 4.0.2 on 2022-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_savings_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costs',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
