# Generated by Django 4.0.2 on 2022-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_rename_created_ad_costs_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incomes',
            new_name='Sources',
        ),
    ]
