# Generated by Django 4.0.2 on 2022-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_rename_incomes_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='expenses',
            field=models.FloatField(default=0),
        ),
    ]
